---
title: "Homework 5"
author: "Amelia Zhao"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document

---

# This is my markdown file for Homework 5. 

# Problem 1: 

```{r}
library(tidyverse)
library(purrr)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) 


fill_na = function(x) {
  if (is.numeric(x) == TRUE) {
    x = x %>% replace_na(
      round(mean(x, na.rm = TRUE, 2)))}
  if (is.character(x) == TRUE) {
    x = x %>% replace_na("virginica")}
  
return(x)
}

iris_with_missing = map_df(iris_with_missing, fill_na)

```


# Problem 2. 


```{r}
"./data"

lookatdata <-
  read_csv("data/exp_07.csv")

studydata <-
  list.files(path = "./data", full.names = TRUE) %>% 
  map(read.csv) %>% 
  reduce(rbind) %>% 
  mutate(
    studyid = c(1:20),
    studygrp = ifelse(
      studyid == c(1:10), "control", "experimental"
    )
  ) %>% 
  janitor::clean_names()

longdata <-
  studydata %>% 
  pivot_longer(week_1:week_8) %>% 
  rename("week" = name) %>% 
  mutate(
    week = str_replace(week, "week_", "")
  )
  

ggplot(data = longdata, aes(x = week, y = value, group = studyid, colour = studygrp)) + geom_line() + labs(
  title = "Figure 1. Values over time for each study participant",
  x = "Week",
  y = "Value") 

```

From Figure 1, we can see that the observed values for the experimental group seem to be generally higher than those in the control group, particularly during the later weeks of the study, when there is no overlap between the study arms at all. 





# Problem 3

```{r}

set.seed(1)

sim_regression = function(n = 30, beta0 = 2, beta1 = 0) {
  sim_data = tibble(
    x = rnorm(n, mean = 0, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, sqrt(50))
    )
  ls_fit = lm(y ~ x, data = sim_data) %>%
  broom::tidy()
  tibble( 
    beta1_hat = ls_fit[[2,2]],
    p_value = ls_fit[[2,5]]
    )
}

sim_results = rerun(100, sim_regression(beta1 = 0)) %>% 
  bind_rows()



```

Jeff why did you make this problem so hard?



